name: Soft_Comp
channels:
- defaults
- conda-forge
dependencies:
- python=2.7.14
- pip:
  - backports-abc==0.5
  - backports.functools-lru-cache==1.5
  - backports.shutil-get-terminal-size==1.0.0
  - cycler==0.10.0
  - ipython-genutils==0.2.0
  - jupyter-client==5.2.2
  - jupyter-core==4.4.0
  - matplotlib==2.1.0
  - nibabel==2.2.0
  - nilearn==0.4.0
  - numpy==1.13.3
  - pandas==0.20.3
  - prompt-toolkit==1.0.15
  - pyparsing==2.2.0
  - pytz==2018.3
  - scikit-learn==0.19.1
  - scipy==0.19.1
  - subprocess32==3.2.7
